name: Deploy Firestore rules and indexes

on:
  push:
    branches:
      - main
    paths:
      - "firestore.indexes.json"
      - "firestore.rules"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g firebase-tools@14.19.1

      - name: Prepare Google Application Credentials
        shell: bash
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > "google-application-credentials.json"

      - name: Deploy to Firebase
        run: |
          firebase deploy --only firestore

      - name: Remove credentials file
        if: success() || failure()
        run: |
          rm google-application-credentials.json

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: emulators-logs
          path: |
            .firebase
            "*-debug.log"
          retention-days: 30
